GCC=gcc 
FLAG= -Wall -g
AR = ar -rcs
POWBASIC=power.o basicMath.o

all: mymaths mymathd mains maind

mymaths: libmyMath.a
libmyMath.a: $(POWBASIC) myMath.h
	$(AR) libmyMath.a $(POWBASIC)

power.o: power.c myMath.h
	$(GCC)$(FLAG) -c power.c

basicMath.o: basicMath.c myMath.h
	$(GCC)$(FLAG) -c basicMath.c

mymathd: libmyMath.so
libmyMath.so: $(POWBASIC) myMath.h
	$(GCC) -shared -o libmyMath.so $(POWBASIC)

mains:main.o mymaths 
	$(GCC)$(FLAG) -o mains main.o libmyMath.a

maind:main.o mymathd 
	$(GCC)$(FLAG) -o maind main.o ./libmyMath.so

main.o:main.c myMath.h
	$(GCC)$(FLAG) -c main.c

.PHONY: clean all mymaths mymathd
clean:
	rm -f *.o *.so *.a maind mains

